### ISSUE TITLE
%v doesn't make sense in naming of snapshot files

### ISSUE THREAD

**Issue by AugustT** [AMI-trap/ami_setup#8]
https://github.com/AMI-trap/ami_setup/blob/ce48f9021d20fbfafdbfc0842ad84dd7a593526c/motion_scripts/motion.conf#L408C12-L408C14

I dont thik we should have the `%v` here, it looks like a mistake to me as the `event` is I think the number of triggers since the beginning of sampling which is only relevant to motion triggered images

@albags @DylanCarbone @gls21

**Comment by AugustT** [comment]
Could the current usage mean that snapshots are counting as an `event`? If so there would not be a triggered image for the same event number and it would look as though there are missing triggered images

**Comment by albags** [comment]
Hi Tom,
The snapshoots were added by Josh and Simon. I think the were following the same nomenclature than the motion/video files. But you are right, the snapshots are independent events so we don't need to track them. I can modify the motion config file.

**Comment by albags** [comment]
I changed the parameter that define the file name for the snapshots to not include the event anymore in the motion.conf file.
